### ISSUE TITLE
Some small cosmetic stuff I noticed

### ISSUE THREAD

**Issue by Pyreko** [Matriz88/hef-website#42]
Disclaimer: these are all _small_ things I noticed and if we don't fix them it's fine; feel free to tackle them and check them off if you want to though!

- [x] Might make more sense to move the close button on the modal to be the standard X? (done in https://github.com/Matriz88/hef-website/commit/8d042ba3a82814df91b2e3ad55c6dbaa3c4f6abc)
- [x] Sidebar close button isn't tab-able (fixed in #43)
- [x] Default to fit-both as that is more intuitive, especially on mobile (fixed in #43)
- [x] Fix progress bar being hidden on mobile until scrolling to the bottom of the page on long strip mode. (fixed in #43)
- [x] Hide sidebar by default on mobile devices as it's very confusing on first open to have half your screen blocked. (fixed in #43)
- [x] Maybe the page next button in the sidebar should not "disable" at the end of a chapter, but go to the next chapter (unless last chapter)? Same with page back. (fixed in #43)
- [ ] Maybe add a page slide animation on mobile when a user swipes? May be hard to implement.
- [x] Add outline around modal tabs as the current colours can get lost in the background. Might also want to tweak the spacing. (fixed in https://github.com/Matriz88/hef-website/pull/47)
  ![image](https://github.com/Matriz88/hef-website/assets/25498386/9a27075c-e0de-4e51-884d-c5ebfffecd40)
  For example you can't see that "reader" is selected here.
- [x] Do we need the back/next buttons in the modal if we have the tabs? (removed those in https://github.com/Matriz88/hef-website/commit/8d042ba3a82814df91b2e3ad55c6dbaa3c4f6abc)
- [x] Maybe add a bit of spacing between keybinds in the modal. (done in https://github.com/Matriz88/hef-website/commit/26c897d61a6de182bf2cb1bfe13bef3a2ed732ed)
- [x] Chapter/page indicators in the header might need some moving, especially on mobile where they move on page change due to sizing issues. (https://github.com/Matriz88/hef-website/pull/48)
- [ ] Might want to play around with some of the spacing between elements in general, like in the sidebar for the chapter title and details.
